# Generated by Django 2.1.1 on 2020-10-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('execution_time', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
