# Generated by Django 2.1.1 on 2020-10-22 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0002_auto_20201021_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='execution_time',
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('dummy', 'ToBeImplemented')], default='dummy', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='request_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
