# Generated by Django 2.1.1 on 2020-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_auto_20201022_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parameters',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('3', 'Exponentiation'), ('2', 'Product'), ('1', 'Summation')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='worker',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
