# Generated by Django 2.1.1 on 2020-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0004_auto_20201024_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_work_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'Summation'), ('3', 'Exponentiation'), ('2', 'Product')], default='0', max_length=20),
        ),
    ]
